#!/bin/bash

for ((i=1;i<=8;i++))
do
    echo $i
    cli.py -s $i < bier_te/bift_entries_s$i
    cli.py -s $i < bier_te/bier_ingress
    cli.py -s $i < bier_te/find_bit_pos
    cli.py -s $i < bier_te/do_cloning_table
    cli.py -s $i < bier_te/do_clone_recirculation_table
    cli.py -s $i < bier_te/mirroring
    cli.py -s $i < bier_te/do_decap_table
    cli.py -s $i < bier_te/do_restore_bier_table
    #cli.py -s $i < bier_te/mc_overlay_s$i
    cli.py -s $i < bier_te/mc_overlay
    #cli.py -s $i < ip_forwarding/entries_s$i
done


